name: task_wave
description: "."


version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  #dependency injection
  get_it: ^7.7.0
  dartz: ^0.10.1

  #state management
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5

  #internet and network
  dio: ^5.5.0+1
  internet_connection_checker: ^1.0.0+1

  #theme and fonts
  flutter_colorpicker: ^1.1.0
  size_config: ^2.0.3

  #utils
  flutter_svg: ^2.0.10+1
  flutter_launcher_icons: ^0.13.1
  intl: ^0.19.0
  pie_chart: ^5.4.0
  android_intent_plus: ^5.1.0
  flutter_week_view: ^1.3.0

  #routing
  go_router: ^14.2.1

  #for board
  flutter_boardview: ^0.2.1

  #local database
  shared_preferences: ^2.2.3
  hive_flutter: ^1.1.0

  #mocking data
  mockito: ^5.4.4
  path_provider: ^2.1.4

  flutter_local_notifications: ^17.2.1+2
  permission_handler: ^11.3.1
  flutter_timezone: ^2.1.0
  syncfusion_flutter_calendar: ^26.2.7

  #firebase
  firebase_core: ^3.3.0

  appcenter_sdk_flutter: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.11
  json_serializable: ^6.8.0
  hive_generator: ^2.0.1
  bloc_test: ^9.1.7
  hive_test: ^1.0.1
  plugin_platform_interface: ^2.1.8
  path_provider_platform_interface: ^2.1.2



flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/png/app_icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

  flutter_lints: ^3.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/png/
    - assets/svg/
    - assets/gif/
